springfox:
  documentation:
    swagger-ui:
      enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:8888/taco_cloud
    username: postgres
    password: iovanevar16
  jpa:
    hibernate:
      ddl-auto: create


#  security:
#    user:
#      name: admin
#      password: admin

server:
  port: 8443
  ssl:
    key-store: mykeys.jks
    key-store-password: letmein
    key-password: letmein

logging:
  file:
    path: /var/logs/
    name: TacoCloud.log
  level:
    root: info
    org.springframework.security: WARN

