INSERT INTO public.ingredient (id, name, type, image_url) VALUES ('SRCR', 'Sour Cream', 'SAUCE', '/ingredients/sour_cream.jpg');
INSERT INTO public.ingredient (id, name, type, image_url) VALUES ('SLSA', 'Salsa', 'SAUCE', '/ingredients/salsa.jpg');
INSERT INTO public.ingredient (id, name, type, image_url) VALUES ('RNCH', 'Ranch', 'SAUCE', '/ingredients/ranch.jpg');
INSERT INTO public.ingredient (id, name, type, image_url) VALUES ('ORNG', 'Orange', 'CITRON', '/ingredients/orange.jpg');
INSERT INTO public.ingredient (id, name, type, image_url) VALUES ('MOJA', 'Monterrey Jack', 'CHEESE', '/ingredients/monterrey_jack.jpg');
INSERT INTO public.ingredient (id, name, type, image_url) VALUES ('LIME', 'Lime', 'CITRON', '/ingredients/lime.jpg');
INSERT INTO public.ingredient (id, name, type, image_url) VALUES ('LETC', 'Lettuce', 'VEGGIES', '/ingredients/lettuce.jpg');
INSERT INTO public.ingredient (id, name, type, image_url) VALUES ('LEMO', 'Lemon', 'CITRON', '/ingredients/lemon.jpg');
INSERT INTO public.ingredient (id, name, type, image_url) VALUES ('GRBF', 'Ground Beef', 'PROTEIN', '/ingredients/ground_beef.jpg');
INSERT INTO public.ingredient (id, name, type, image_url) VALUES ('FLTO', 'Flour Tortilla', 'WRAP', '/ingredients/flour_tortilla.jpg');
INSERT INTO public.ingredient (id, name, type, image_url) VALUES ('DITM', 'Diced Tomatoes', 'VEGGIES', '/ingredients/diced_tomatoes.jpg');
INSERT INTO public.ingredient (id, name, type, image_url) VALUES ('COTO', 'Corn Tortilla', 'WRAP', '/ingredients/corn_tortilla.jpg');
INSERT INTO public.ingredient (id, name, type, image_url) VALUES ('CHED', 'Cheddar', 'CHEESE', '/ingredients/cheddar.jpg');
INSERT INTO public.ingredient (id, name, type, image_url) VALUES ('CARN', 'Carnitas', 'PROTEIN', '/ingredients/carnitas.jpg');